port:  5000
markdown: kramdown
name: "Stop Child Labor in the Tobacco Industry"
url: https://100millionsignup.netlify.com/
encoding: utf-8
timezone: America/Chicago
description: "Enter your address to find and contact your federal, state, county and local elected representatives"
gems:
  - jekyll-redirect-from
google_api_key: AIzaSyBk3MvVDmqDF_scPL3mO-psJV6WwVlx47c
  #AIzaSyCPBjxbj0KC9YXxTQjGuWykxLTZRyiQ1kQ